sonar.projectKey=harounn07_pfefinal
sonar.organization=harounn07

sonar.sources=todo-backend/src,todo-frontend/src
sonar.tests=todo-backend/tests

sonar.sourceEncoding=UTF-8

sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/.next/**,**/coverage/**

sonar.test.exclusions=**/*.test.js,**/*.spec.js

sonar.javascript.lcov.reportPaths=todo-backend/coverage/lcov.info