sonar.projectKey=harounn07_pfefinal
sonar.organization=harounn07

sonar.sources=.
sonar.sourceEncoding=UTF-8

# ❌ EXCLUDE FRONTEND COMPLETELY
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/.next/**,**/coverage/**,todo-frontend/**

# ✅ TESTS
sonar.test.inclusions=todo-backend/tests/**/*.test.js

# ✅ sCOVERAGE PATH
sonar.javascript.lcov.reportPaths=todo-backend/coverage/lcov.info