sonar.projectKey=harounn07_pfefinal
sonar.organization=harounn07

sonar.sources=.
sonar.sourceEncoding=UTF-8

sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/.next/**,**/coverage/**

sonar.test.exclusions=**/*.test.js,**/*.spec.js,**/*.test.ts,**/*.spec.ts