sonar.projectKey=harounn07_pfefinal
sonar.organization=harounn07

sonar.sources=.
sonar.sourceEncoding=UTF-8

# exclude useless stuff
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/.next/**

# ✅ tell sonar where tests are
sonar.tests=.
sonar.test.inclusions=**/*.test.js

# ✅ coverage file
sonar.javascript.lcov.reportPaths=coverage/lcov.info