- name: Deploy Docker App
  hosts: app
  become: false

  vars_files:
    - secrets.yml

  tasks:

    - name: Install Git
      become: true
      dnf:
        name: git
        state: present

    - name: Install Docker Compose v2 manually
      become: true
      shell: |
        mkdir -p /usr/local/lib/docker/cli-plugins
        curl -SL https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64 \
          -o /usr/local/lib/docker/cli-plugins/docker-compose
        chmod +x /usr/local/lib/docker/cli-plugins/docker-compose

        mkdir -p /usr/libexec/docker/cli-plugins
        cp /usr/local/lib/docker/cli-plugins/docker-compose /usr/libexec/docker/cli-plugins/docker-compose

    - name: Create app directory
      become: true
      file:
        path: /home/ec2-user/app
        state: directory
        owner: ec2-user
        group: ec2-user

    - name: Fix ownership
      become: true
      file:
        path: /home/ec2-user/app
        owner: ec2-user
        group: ec2-user
        recurse: yes

    - name: Clone project repo
      git:
        repo: "https://github.com/harounn07/pfefinal.git"
        dest: /home/ec2-user/app
        force: yes

    
    - name: Create .env file from Vault
      become: true
      copy:
        dest: /home/ec2-user/app/.env
        owner: ec2-user
        group: ec2-user
        content: |
          PORT=3001
          DB_HOST={{ db_host }}
          DB_PORT={{ db_port }}
          DB_USER={{ db_user }}
          DB_PASSWORD={{ db_password }}
          DB_NAME={{ db_name }}
          DB_SSL={{ db_ssl }}
          JWT_SECRET={{ jwt_secret }}
          JWT_EXPIRES_IN={{ jwt_expires_in }}
          CORS_ORIGIN={{ cors_origin }}

    - name: Stop old compose
      command: docker compose down --remove-orphans
      args:
        chdir: /home/ec2-user/app
      ignore_errors: yes

    - name: Force remove containers
      shell: docker rm -f $(docker ps -aq) || true

    - name: Run docker compose
      command: docker compose up -d --build
      args:
        chdir: /home/ec2-user/app