[app]
10.0.11.140
10.0.12.49

[all:vars]
ansible_user=ec2-user
ansible_ssh_private_key_file=~/sssh/devops-key.pem
ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -i ~/sssh/devops-key.pem ec2-user@51.20.98.229"'