name: DevSecOps CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:

      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Install Node
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Lint code
      - name: Run ESLint
        run: npx eslint . || true

      # Run tests
      - name: Run Tests
        run: npm test || echo "No tests"

      # Secret scanning
      - name: Gitleaks Scan
        uses: gitleaks/gitleaks-action@v2

      # Build backend image
      - name: Build Backend Image
        run: docker build -t pfefinal-backend ./todo-backend

      # Build frontend image
      - name: Build Frontend Image
        run: docker build -t pfefinal-frontend ./todo-frontend

      # Scan backend image
      - name: Trivy Backend Scan
        uses: aquasecurity/trivy-action@v0.35.0
        with:
          image-ref: 'pfefinal-backend'
          severity: 'CRITICAL,HIGH'
          exit-code: '1'
          trivyignores: './todo-backend/.trivyignore'

      # Scan frontend image
      - name: Trivy Frontend Scan
        uses: aquasecurity/trivy-action@v0.35.0
        with:
          image-ref: 'pfefinal-frontend'
          severity: 'CRITICAL,HIGH'
          exit-code: '1'
          trivyignores: './todo-frontend/.trivyignore'