name: DevSecOps CI Pipeline

on:
push:
branches:
- main
- dev
pull_request:

jobs:
ci:
runs-on: ubuntu-latest


steps:

  # 1. Checkout code
  - name: Checkout Code
    uses: actions/checkout@v4

  # 2. Setup Node
  - name: Setup Node
    uses: actions/setup-node@v4
    with:
      node-version: 18

  # 3. Install Backend dependencies
  - name: Install Backend deps
    run: |
      cd todo-backend
      npm install

  # 4. Install Frontend dependencies
  - name: Install Frontend deps
    run: |
      cd todo-frontend
      npm install

  # 5. Lint Backend
  - name: Run ESLint Backend
    run: |
      cd todo-backend
      npx eslint . || true

  # 6. Lint Frontend
  - name: Run ESLint Frontend
    run: |
      cd todo-frontend
      npx eslint . || true

  # 7. Run Backend Tests
  - name: Run Backend Tests
    run: |
      cd todo-backend
      npm test || echo "No backend tests"

  # 8. Run Frontend Tests
  - name: Run Frontend Tests
    run: |
      cd todo-frontend
      npm test || echo "No frontend tests"

  # 9. SonarCloud Scan
  - name: SonarCloud Scan
    uses: SonarSource/sonarcloud-github-action@v2
    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    with:
      args: >
        -Dsonar.projectKey=pfe-devsecops
        -Dsonar.organization=your-org

  # 10. Secret Scan (Gitleaks)
  - name: Gitleaks Scan
    uses: gitleaks/gitleaks-action@v2

  # 11. Build Backend Docker Image
  - name: Build Backend Image
    run: docker build -t pfefinal-backend ./todo-backend

  # 12. Build Frontend Docker Image
  - name: Build Frontend Image
    run: docker build -t pfefinal-frontend ./todo-frontend

  # 13. Scan Backend Image (Trivy)
  - name: Trivy Backend Scan
    uses: aquasecurity/trivy-action@0.28.0
    with:
      image-ref: 'pfefinal-backend'
      severity: 'CRITICAL,HIGH'
      exit-code: '1'
      ignore-unfixed: true

  # 14. Scan Frontend Image (Trivy)
  - name: Trivy Frontend Scan
    uses: aquasecurity/trivy-action@0.28.0
    with:
      image-ref: 'pfefinal-frontend'
      severity: 'CRITICAL,HIGH'
      exit-code: '1'
      ignore-unfixed: true

