name: DevSecOps CI Pipeline

on:
  push:
    branches:
      - main
      - dev
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npx eslint . || true

      - name: Run Tests
        run: npm test || echo "No tests"

      # SONARQUBE ANALYSIS
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      # SECRET SCAN
      - name: Gitleaks Scan
        uses: gitleaks/gitleaks-action@v2

      # BUILD BACKEND IMAGE
      - name: Build Backend Image
        run: docker build -t pfefinal-backend ./todo-backend

      # BUILD FRONTEND IMAGE
      - name: Build Frontend Image
        run: docker build -t pfefinal-frontend ./todo-frontend

      # SECURITY SCAN BACKEND
      - name: Trivy Backend Scan
        uses: aquasecurity/trivy-action@v0.19.0
        with:
          image-ref: 'pfefinal-backend'
          severity: 'CRITICAL,HIGH'
          exit-code: '1'
          ignorefile: .trivyignore

      # SECURITY SCAN FRONTEND
      - name: Trivy Frontend Scan
        uses: aquasecurity/trivy-action@v0.19.0
        with:
          image-ref: 'pfefinal-frontend'
          severity: 'CRITICAL,HIGH'
          exit-code: '1'