name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

env:
  AWS_REGION: eu-north-1
  ECR_REGISTRY: 367560037937.dkr.ecr.eu-north-1.amazonaws.com

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    # 1. Checkout
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. AWS creds
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    # 3. Login ECR
    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2

    # 4. Build backend
    - name: Build & push backend
      run: |
        docker build -t $ECR_REGISTRY/pfefinal-backend:latest ./todo-backend
        docker push $ECR_REGISTRY/pfefinal-backend:latest

    # 5. Build frontend
    - name: Build & push frontend
      run: |
        docker build -t $ECR_REGISTRY/pfefinal-frontend:latest ./todo-frontend
        docker push $ECR_REGISTRY/pfefinal-frontend:latest

    # 6. Deploy عبر Bastion
    - name: Deploy via Bastion
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: 10.0.11.140
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}

        proxy_host: ${{ secrets.EC2_HOST }}
        proxy_username: ec2-user
        proxy_key: ${{ secrets.EC2_SSH_KEY }}

        script: |
          echo "=== CONNECTED TO EC2 ==="

          cd /home/ec2-user/app

          echo "=== PULL LATEST CODE ==="
          git pull origin main

          echo "=== LOGIN TO ECR ==="
          aws ecr get-login-password --region eu-north-1 | \
          docker login --username AWS --password-stdin $ECR_REGISTRY

          echo "=== PULL IMAGES ==="
          docker compose pull

          echo "=== RESTART CONTAINERS ==="
          docker compose down
          docker compose up -d --force-recreate

          echo "=== DONE ==="